### ISSUE TITLE
Add code formatter

### ISSUE THREAD

**Issue by ginic** [UMassCDS/PythonProjectTemplate#8]
Automated Code Formatting: Code formatter [Ruff](https://github.com/astral-sh/ruff) can help maintain a consistent code style across the project, making it easier to read and understand.

Definition of done: 
- Add information on using ruff as an automatic code formatter to the README
- Add links for setting up ruff in VS Code and PyCharm

**Comment by lukeruud** [comment]
I'm working on this!
